name: ci

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    runs-on: macos-13
    strategy:
      fail-fast: false
      matrix:
        arch: [x86_64, arm64]

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install dependencies (x86)
        if: ${{ matrix.arch == 'x86_64' }}
        run: |
          brew install \
            boost \
            extra-cmake-modules \
            glog gflags yaml-cpp leveldb lua \
            ninja

      - name: Setup arm homebrew
        if: ${{ matrix.arch == 'arm64' }}
        uses: fcitx-contrib/macos-cross@master

      - name: Install dependencies (arm)
        if: ${{ matrix.arch == 'arm64' }}
        run: |
          brew install \
            extra-cmake-modules \
            ninja
          arm-brew-install \
            zstd \
            glog gflags yaml-cpp leveldb lua \
            boost

      - name: Download and extract Fcitx5.app
        run: |
          wget https://github.com/fcitx-contrib/fcitx5-macos/releases/download/latest/Fcitx5-${{ matrix.arch }}.dmg
          hdiutil attach Fcitx5-${{ matrix.arch }}.dmg
          sudo cp -r /Volumes/Fcitx5/{Fcitx5.app,"Input Methods"}

      - name: Build all
        run: ./all.sh ${{ matrix.arch }}

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: artifact-${{ matrix.arch }}
          path: |
            build/*.tar.bz2

      - name: Setup tmate session
        if: ${{ failure() }}
        uses: mxschmitt/action-tmate@v3

  release:
    needs: build
    if: ${{ github.ref == 'refs/heads/master' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          merge-multiple: true

      - name: Repackage arm
        run: ./fix-cross-build.sh

      - name: Release
        uses: 'marvinpinto/action-automatic-releases@latest'
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          automatic_release_tag: latest
          prerelease: true
          title: "Nightly Build"
          files: |
            *.tar.bz2
